### PR TITLE
Remove the log4j wrappers and write directly to stdout.

### PR DESCRIPTION
**Pull request by jamezp**
I don't really understand why we'd write to an output stream which configures a log manager for a command line tool. That seems odd to me. My proposal would be to remove logging all together.

I also think this should be done in a major or minor release and not a micro.

### CODE REVIEW

**Comment by jimma** [comment]
@jamezp  Thanks for the change. I checked the jbossws and cxf code, and it looks we remove this log4j dependency in jbossws-common-tools.

**Comment by marekkopecky** [comment]
@jamezp @jimma I'm looking into WF, and it seems that wf is still using old version of ws tools (1.3.2.Final), so this new changes is not there. Is there some plan for update ws-tools in wildfly? cc @jbliznak

**Comment by jamezp** [comment]
@marekkopecky That is a good question. I'm not too sure TBH. I was just attempting to help with cleaning up the log4j usage. I don't know the release plans for this.

**Comment by marekkopecky** [comment]
@jimma (cc @asoldano ) Is there some plan for update ws-tools in wildfly?

**Comment by jimma** [comment]
@marekkopecky  I'll upgrade the 1.4.0.Final in WFLY later.

**Comment by marekkopecky** [comment]
@jimma Do you have some ETA? In which release? See also related jira https://issues.redhat.com/browse/JBEAP-9379

**Pull request merged**
